/// After her "no" to location, the map says 位置情報オフ, not 現在地不明.
///
/// WHY, written before the act. Ruled 2026-09-13 on the refusal surface: a
/// permission result is the platform's exact answer, so it gets its own words.
/// What matters to her is that location is off for this app and will not come
/// back by itself, and her decision is shown as a setting, not as a machine
/// fault. The words describe the setting and never say that she refused:
/// Android can deny without her taking any action.
///
/// Pinned here, as decided:
/// * the class is her answer only: permission denied, and denied for good.
///   Location services off stays on 現在地不明;
/// * the class is TYPED, never read from free text: a reason string can carry
///   exception text, and matching into it could silence a real failure;
/// * map: the same top-centre pill, key `her-location-off-label`, in the
///   refusal branch, which must not require `positionLost`;
/// * the line under the map: the decided strings, byte-exact, whose head is the
///   same bytes as the pill; only a permanent denial gets the settings hint;
/// * no icon, no button; a screen reader hears it once, as one live region;
/// * it clears on 停止 and on re-share.
library;

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:geolocator/geolocator.dart';
import 'package:sngnav_app/akita_map.dart';
import 'package:sngnav_app/her_position.dart';
import 'package:sngnav_app/jma_fetch.dart';
import 'package:sngnav_app/l10n/app_localizations.dart';
import 'package:sngnav_app/main.dart' show SngnavApp;

import '../support/fake_alert_actuators.dart';

// Byte-exact from the decided strings table of 2026-09-13, generated by script
// from that table, never retyped. English head then decided by the interface
// review the same day: "No location access" rather than "Location off", which
// blurred into "Position off this map"; the line under the map changes to
// match, and the Japanese stays.
const _mapJa = '位置情報オフ';
const _mapEn = 'No location access';
const _deniedJa =
    '位置情報オフ — このアプリには位置情報へのアクセスが許可されていません。地図は表示されたままです。ルート欄はタップで引き続き使えます。';
const _deniedEn =
    'No location access — location permission is off for this app. The map remains; the route panel still works by tap.';
const _foreverJa =
    '位置情報オフ — このアプリには位置情報へのアクセスが許可されていません。変更する場合は端末の設定から行えます。地図は表示されたままです。ルート欄はタップで引き続き使えます。';
const _foreverEn =
    'No location access — location permission is off for this app. If you want to change this, you can do so in the device settings. The map remains; the route panel still works by tap.';

const _offKey = ValueKey('her-location-off-label');
const _unknownKey = ValueKey('her-position-unknown-label');
const _statusKey = Key('her-status-line');

/// A 1x1 transparent PNG, so the basemap never reaches for the network.
final _blankTile = Uint8List.fromList(const <int>[
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, //
  0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, //
  0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, //
  0x0B, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x60, 0x00, 0x02, 0x00, //
  0x00, 0x05, 0x00, 0x01, 0x7A, 0x5E, 0xAB, 0x3F, 0x00, 0x00, 0x00, 0x00, //
  0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82, //
]);

class _BlankTileProvider extends TileProvider {
  @override
  ImageProvider getImage(TileCoordinates coordinates, TileLayer options) =>
      MemoryImage(_blankTile);
}

/// Semantics nodes, anywhere in the tree, that are live regions and whose
/// label carries [text].
int _liveRegionsSaying(WidgetTester tester, String text) {
  var node = tester.getSemantics(find.byType(Scaffold));
  while (node.parent != null) {
    node = node.parent!;
  }
  var n = 0;
  void visit(SemanticsNode node) {
    final data = node.getSemanticsData();
    if (data.flagsCollection.isLiveRegion && data.label.contains(text)) n++;
    node.visitChildren((child) {
      visit(child);
      return true;
    });
  }

  visit(node);
  return n;
}

JmaObservation _clearObs() => JmaObservation(
      stationId: '32402',
      stationName: '秋田',
      temperatureCelsius: 15.0,
      humidityPercent: 30,
      windMetersPerSecond: 1.0,
      snowDepthCm: null,
      precipitation10mMm: 0.0,
      visibilityMeters: null,
      observedAtJstKey: '20260115063000',
      fetchedAt: DateTime(2026, 7, 15, 6, 30),
    );

Stream<PositionFix> _denied() => herPositionStream(
      isServiceEnabled: () async => true,
      checkPermission: () async => LocationPermission.denied,
      requestPermission: () async => LocationPermission.denied,
    );

Stream<PositionFix> _deniedForever() => herPositionStream(
      isServiceEnabled: () async => true,
      checkPermission: () async => LocationPermission.deniedForever,
    );

Stream<PositionFix> _servicesOff() =>
    herPositionStream(isServiceEnabled: () async => false);

Future<void> _pumpMap(WidgetTester tester,
    {required bool refused,
    required bool lost,
    Locale locale = const Locale('ja')}) async {
  await tester.pumpWidget(MaterialApp(
    locale: locale,
    localizationsDelegates: const [
      AppL10n.delegate,
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: AppL10n.supportedLocales,
    home: Scaffold(
      body: Align(
        alignment: Alignment.topLeft,
        child: SizedBox(
          width: 361,
          child: AkitaMap(
            height: 320,
            baseTileProvider: _BlankTileProvider(),
            positionRefused: refused,
            positionLost: lost,
            positionDegraded: lost,
          ),
        ),
      ),
    ),
  ));
  await tester.pump();
}

void main() {
  group('the class: typed, her answer only', () {
    test('denied, and denied for good, read from the real position stream',
        () async {
      final denied = await _denied().first;
      final forever = await _deniedForever().first;
      expect(isLocationRefusal(denied), isTrue);
      expect(isPermanentLocationRefusal(denied), isFalse);
      expect(isLocationRefusal(forever), isTrue);
      expect(isPermanentLocationRefusal(forever), isTrue);
    });

    test('location services off is not in the class', () async {
      final off = await _servicesOff().first;
      expect(off, isA<PositionUnavailable>(), reason: 'control');
      expect(isLocationRefusal(off), isFalse);
    });

    test(
        'free text is never read: an unavailability whose reason merely SAYS '
        '"Location permission denied" is not a refusal', () {
      const spoofed = PositionUnavailable('Location permission denied');
      const spoofedForever = PositionUnavailable(
          'Location permission permanently denied — change in OS settings');
      const streamError =
          PositionUnavailable('GPS stream error: Location permission denied');
      expect(isLocationRefusal(spoofed), isFalse);
      expect(isLocationRefusal(spoofedForever), isFalse);
      expect(isLocationRefusal(streamError), isFalse);
    });
  });

  group('the map pill', () {
    testWidgets(
        'refused and NOT lost: 位置情報オフ at the top (a refusal does not '
        'reach the drive brain, so lost is never set)', (tester) async {
      await _pumpMap(tester, refused: true, lost: false);
      final pill = find.byKey(_offKey);
      expect(pill, findsOneWidget);
      expect(find.descendant(of: pill, matching: find.text(_mapJa)),
          findsOneWidget);
      final map = tester.getRect(find.byType(AkitaMap));
      expect(tester.getRect(pill).top - map.top, lessThanOrEqualTo(16));
      expect(find.byKey(_unknownKey), findsNothing);
    });

    testWidgets('refused and lost: still 位置情報オフ, not 現在地不明',
        (tester) async {
      await _pumpMap(tester, refused: true, lost: true);
      expect(find.byKey(_offKey), findsOneWidget);
      expect(find.byKey(_unknownKey), findsNothing);
    });

    testWidgets('English: "No location access"', (tester) async {
      await _pumpMap(tester,
          refused: true, lost: false, locale: const Locale('en'));
      expect(
          find.descendant(of: find.byKey(_offKey), matching: find.text(_mapEn)),
          findsOneWidget);
    });

    testWidgets('lost and not refused: 現在地不明, unchanged', (tester) async {
      await _pumpMap(tester, refused: false, lost: true);
      expect(find.byKey(_unknownKey), findsOneWidget);
      expect(find.byKey(_offKey), findsNothing);
    });

    testWidgets('no icon and no button inside it', (tester) async {
      await _pumpMap(tester, refused: true, lost: false);
      final pill = find.byKey(_offKey);
      expect(pill, findsOneWidget);
      expect(find.descendant(of: pill, matching: find.byType(Icon)),
          findsNothing);
      expect(
          find.descendant(
              of: pill, matching: find.byWidgetPredicate((w) => w is ButtonStyleButton)),
          findsNothing);
      expect(
          find.descendant(
              of: pill, matching: find.byWidgetPredicate((w) => w is GestureDetector)),
          findsNothing);
    });

    testWidgets('a screen reader hears it once: exactly one live region',
        (tester) async {
      final handle = tester.ensureSemantics();
      await _pumpMap(tester, refused: true, lost: false);
      expect(_liveRegionsSaying(tester, _mapJa), 1);
      handle.dispose();
    });
  });

  group('in the real app', () {
    Future<FakeAlertActuators> share(WidgetTester tester,
        Stream<PositionFix> Function() source,
        {Locale locale = const Locale('ja')}) async {
      final actuators = FakeAlertActuators();
      await tester.pumpWidget(const SizedBox.shrink());
      await tester.pump();
      await tester.pumpWidget(SngnavApp(
      // Not about the consent act; that is guarded in
      // test/widgets/location_consent_act_and_privacy_surface_test.dart.
      locationConsent: true,

        actuators: actuators,
        locale: locale,
        clock: DateTime.now,
        jmaFetch: () async => JmaSuccess(_clearObs()),
        positionSource: source,
      ));
      await tester.pump();
      await tester.pump();
      final button = find.byKey(const Key('share-location-button'));
      await tester.ensureVisible(button);
      await tester.pump();
      await tester.tap(button);
      await tester.pump();
      await tester.pump();
      await tester.pump();
      return actuators;
    }

    String? status(WidgetTester tester) {
      final f = find.byKey(_statusKey);
      return f.evaluate().isEmpty ? null : tester.widget<Text>(f).data;
    }

    for (final (name, source, locale, map, line) in [
      ('denied, Japanese', _denied, const Locale('ja'), _mapJa, _deniedJa),
      ('denied, English', _denied, const Locale('en'), _mapEn, _deniedEn),
      ('denied for good, Japanese', _deniedForever, const Locale('ja'), _mapJa,
          _foreverJa),
      ('denied for good, English', _deniedForever, const Locale('en'), _mapEn,
          _foreverEn),
    ]) {
      testWidgets('$name: the pill and the decided line, byte-exact',
          (tester) async {
        await share(tester, source, locale: locale);
        expect(
            find.descendant(of: find.byKey(_offKey), matching: find.text(map)),
            findsOneWidget);
        expect(find.byKey(_unknownKey), findsNothing);
        expect(status(tester), line);
        expect(status(tester)!.startsWith('$map — '), isTrue,
            reason: 'the head of the line is the same bytes as the pill');
      });
    }

    testWidgets('location services off: 現在地不明 and its line, unchanged',
        (tester) async {
      await share(tester, _servicesOff);
      expect(find.byKey(_unknownKey), findsOneWidget);
      expect(find.byKey(_offKey), findsNothing);
      expect(status(tester),
          'GPS を取得できません — 位置情報サービスが無効です。地図は表示されたままです。ルート欄はタップで引き続き使えます。');
    });

    testWidgets(
        'after a denial the row offers 閉じる / "Close", not 停止 / "Stop"; '
        'in a sharing session it still offers 停止', (tester) async {
      await share(tester, _denied);
      expect(find.text('閉じる'), findsOneWidget);
      expect(find.text('停止'), findsNothing,
          reason: 'no Stop for a session that never started');

      await share(tester, _denied, locale: const Locale('en'));
      expect(find.text('Close'), findsOneWidget);
      expect(find.text('Stop'), findsNothing);

      await share(tester, _servicesOff);
      expect(find.text('停止'), findsOneWidget,
          reason: 'control: location services off is not a denial');
      expect(find.text('閉じる'), findsNothing);
    });

    testWidgets('it clears on 閉じる, and on a re-share', (tester) async {
      var answer = LocationPermission.denied;
      await share(
          tester,
          () => herPositionStream(
                isServiceEnabled: () async => true,
                checkPermission: () async => answer,
                requestPermission: () async => answer,
                positionStream: () => const Stream<Position>.empty(),
              ));
      expect(find.byKey(_offKey), findsOneWidget, reason: 'control');

      await tester.ensureVisible(find.text('閉じる'));
      await tester.pump();
      await tester.tap(find.text('閉じる'));
      await tester.pump();
      expect(find.byKey(_offKey), findsNothing, reason: 'cleared on 閉じる');
      expect(find.byKey(const Key('share-location-button')), findsOneWidget,
          reason: 'the same action as 停止: sharing has ended');

      // She allows location this time; before any fix arrives, the words
      // from her previous answer must already be gone.
      answer = LocationPermission.whileInUse;
      final button = find.byKey(const Key('share-location-button'));
      await tester.ensureVisible(button);
      await tester.pump();
      await tester.tap(button);
      await tester.pump();
      expect(find.byKey(_offKey), findsNothing, reason: 'cleared on re-share');
    });
  });
}
